/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ZTDrawerState } from "./components/zt-bottom-drawer/drawer-state";
export namespace Components {
    interface ZtBottomDrawer {
        "addCallbackCanActivateState": (callback: (state: ZTDrawerState, oldState: ZTDrawerState, drawerElement: HTMLElement, contentElement: HTMLElement) => Promise<boolean | void> | void) => Promise<void>;
        "addCallbackCanDeactivateState": (callback: (state: ZTDrawerState, newState: ZTDrawerState, drawerElement: HTMLElement, contentElement: HTMLElement) => Promise<boolean | void> | void) => Promise<void>;
        "autoHeightContent": boolean;
        "disableMove": boolean;
        "distanceBottomClose": number;
        "distanceBottomOpen": number;
        "distanceTopFullOpen": number;
        "easing": string;
        "state": ZTDrawerState;
    }
}
declare global {
    interface HTMLZtBottomDrawerElement extends Components.ZtBottomDrawer, HTMLStencilElement {
    }
    var HTMLZtBottomDrawerElement: {
        prototype: HTMLZtBottomDrawerElement;
        new (): HTMLZtBottomDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "zt-bottom-drawer": HTMLZtBottomDrawerElement;
    }
}
declare namespace LocalJSX {
    interface ZtBottomDrawer {
        "autoHeightContent"?: boolean;
        "disableMove"?: boolean;
        "distanceBottomClose"?: number;
        "distanceBottomOpen"?: number;
        "distanceTopFullOpen"?: number;
        "easing"?: string;
        "onChangeState"?: (event: CustomEvent<ZTDrawerState>) => void;
        "onCloseBottom"?: (event: CustomEvent<void>) => void;
        "state"?: ZTDrawerState;
    }
    interface IntrinsicElements {
        "zt-bottom-drawer": ZtBottomDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "zt-bottom-drawer": LocalJSX.ZtBottomDrawer & JSXBase.HTMLAttributes<HTMLZtBottomDrawerElement>;
        }
    }
}
